---
- name: Install and configure Tomcat - 2022
  hosts: 192.168.2.30
  become: yes

  vars:
<<<<<<< HEAD
    ansible_become_password: "{{ mypass }}"
=======
    ansible_become_password: "vagrant"
>>>>>>> 01108c2a53604a402a73d5c7841369ccb9cfefee

  tasks:
    - name: install tomcat
      ansible.builtin.yum:
        name: 
          - tomcat
          - tomcat-webapps
          - tomcat-admin-webapps
          - tomcat-docs-webapp
        state: present

    - name: start tomcat
      ansible.builtin.service:
        name: tomcat
        state: started

    - name: copy install_tomcat.yml file
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: /usr/share/tomcat/conf/tomcat-users.xml
        group: tomcat
        mode: 0644
    
    - name: restart tomcat
      ansible.builtin.service:
        name: tomcat
        state: restarted



